config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists, except: %i[edit update] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }

end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy]

  def index
    @lists = List.all
  end

  def show; end

  def new
    @list = List.new
    @movies = Movie.all
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="d-flex align-items-center px-3">
  <h1 class="col-2-md mt-2 ms-2">Add movie to <strong><u><%= @list.name %></u></strong></h1>
  <p class="flex-grow-1"></p>
  <%= link_to "Back", root_path, class: "col-2-md button-rounded bg-primary"  %>
</div>
<div class="wrapper bg-body mt-4">
  <div class="container w-25 pt-2 pb-4 bg-body fs-4">
    <%= simple_form_for [@list, @bookmark]  do |f| %>
    <%= f.input :comment%>
    <%= f.association :movie %>
    <%= f.button :submit, "Add to list", class: "button-rounded bg-success" %>
  <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
  <div class="fixed-bottom mt-4 py-0 px-3 card text-bg-dark d-flex flex-row align-items-center">
    <p class="pt-2 mb-0 pb-1 fw-lighter ">🤖 This page was generated by AI bootcamp students.</p>
    <div class="flex-grow-1"></div>
    <%= link_to icon('fa-regular', 'gem'), '#', class: 'text-danger' %>
    <%= link_to icon('fa-brands', 'instagram'), '#', class: 'text-pink mx-2' %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>

    <%# <%= render "layouts/footer" %> %>

  </body>
</html>

app/views/lists/index.html.erb
<div class="d-flex align-items-center px-3 mb-4">
  <h1 class="col-2-md mt-2 ms-2"><b>Your movie lists</b></h1>
  <p class="flex-grow-1"></p>
  <%= link_to "Create a new list", new_list_path, class: "button-rounded bg-info" %>
</div>
<%= image_tag ["popcorn.jpg", "posters.jpg", "posters3.jpg", "projector.jpg", "remote.jpg", "scoff.jpg", "jaws.jpg", "Silence.jpg", "starwars.jpg", "breaky.jpg"].sample, alt: "Popcorn", class: "hero" %>
<div class="container d-flex flex-wrap">
  <% @lists.each do |list| %>
    <%= link_to list_path(list), class: "text-decoration-none text-dark" do %>
      <div class="card h-100 w-50 mb-3 me-2 p-2 pb-0 shadow-sm">
      <% if list.movies.exists? %>
        <%= image_tag list.movies.first.poster_url, class: "image-list" %>
      <% else %>
        <div class="image-list"></div>
      <% end %>
      <h3><%= list.name %></h3>
      <div class="h-100 mb-2 d-flex justify-content-start align-items-center">
        <% list.movies.each do |movie| %>
          <div class="me-2 badge text-dark" style="background: lightgray">
            <%= movie.title %>
          </div>
        <% end %>
      </div>
    <% end %>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="d-flex align-items-center px-3">
  <h1 class="col-2-md mt-2 ms-2">Add new list</h1>
  <p class="flex-grow-1"></p>
  <%= link_to "Back", root_path, class: "col-2-md button-rounded bg-primary"  %>
</div>
<div class="container w-50 mt-4">
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.button :submit, "Save", class: "button-rounded bg-success" %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="d-flex align-items-center px-3">
  <h1 class="col-2-md mt-2 ms-2"><b><%= @list.name.capitalize %>:</b> <span class="text-info"><%= @list.bookmarks.size %> movies</span></h1>
  <p class="flex-grow-1"></p>
  <%= link_to "Back", root_path, class: "button-rounded bg-primary" %>
</div>
<div class="container">
  <div class="pt-4">
    <% @list.bookmarks.all.each do |bookmark| %>
      <div class="col w-50 mb-3 p-3 rounded bg-black opacity-75 shadow-sm text-white">
        <%= image_tag bookmark.movie.poster_url, alt: bookmark.movie.title, class: "poster" %>
        <h4><%= bookmark.movie.title %>  <span class="fw-light text-info"><%= bookmark.movie.rating %></span></h4>
        <p><%= bookmark.movie.overview %></p>
        <div class="d-flex flex-row m-0 p-0">
          <p class="ms-2"><span class="fs-4">"</span><%= bookmark.comment %><span class="fs-4">"</span></p>
          <div class="flex-grow-1"></div>
          <%= link_to "Delete",
            bookmark_path(bookmark),
            data: {turbo_method: :delete, turbo_confirm: "Remove movie from list?"},
            class: "button-rounded border border-danger fw-semibold text-danger"
          %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <%= link_to "Add movie to list", new_list_bookmark_path(@list), class: "col-2 me-3 button-rounded bg-info fw-bold" %>
    <%= link_to "Remove list",
      list_path(@list),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
      class: "col-2 button-rounded bg-danger fw-bold"
    %>
  </div>
</div>